### ISSUE TITLE
加入pod

### ISSUE THREAD

**Issue by lanhaoxiang** [weng1250/WZLBadge#1]
不错的工程，赞一个，能加入cocoapod支持就完美了

**Comment by weng1250** [comment]
Thanks your issue. I am now also considering supporting cocoapods for WZLBadge project. Thanks your attention ^_^ New version will be released recently.

**Comment by Ewg777** [comment]
+1. It'll be perfect

**Comment by weng1250** [comment]
Yea! pod support for WZLBadge has been finished and is now checking by CocoaPods team. It is on the way.

**Comment by lanhaoxiang** [comment]
great job!
