### ISSUE TITLE
pod 1.2版本 安装有问题

### ISSUE THREAD

**Issue by lkqin** [weng1250/WZLBadge#11]
缺少这两个
#import "UIBarButtonItem+WZLBadge.h"
#import "UITabBarItem+WZLBadge.h"
![image](https://cloud.githubusercontent.com/assets/13670037/10154004/c745d496-6694-11e5-8246-331239409702.png)

**Comment by weng1250** [comment]
Thanks for your committed issue. We have fixed it.
