### ISSUE TITLE
deprecated warning

### ISSUE THREAD

**Issue by fdddf** [weng1250/WZLBadge#12]
WZLBadge/View/UIView+WZLBadge.m:153:27: 'sizeWithFont:constrainedToSize:lineBreakMode:' is deprecated: first deprecated in iOS 7.0 - Use -boundingRectWithSize:options:attributes:context:

**Comment by jfuellert** [comment]
It looks like "Custom badge font #13" fixes this warning.

**Comment by weng1250** [comment]
Just as jfuellert said, it was fixed in #13
