### ISSUE TITLE
self.navigationItem.rightBarButtonItem 调整小圆点的位置，没有作用

### ISSUE THREAD

**Issue by mg459046365** [weng1250/WZLBadge#15]
self.giftItem.badgeCenterOffset = CGPointMake(50, 0);
    self.navigationItem.rightBarButtonItem = self.giftItem;
    [self.navigationItem.rightBarButtonItem showBadge];
    self.navigationItem.rightBarButtonItem.badgeCenterOffset = CGPointMake(50, 0);
都没有效果

**Comment by mg459046365** [comment]
放到我项目里，badge的位置死活调不了，新建一个项目就可以设置了，不知道为什么

**Comment by mg459046365** [comment]
发现直接调用[item showBadge]，无法调整位置；而调用[item showBadgeWithStyle:WBadgeStyleRedDot value:0 animationType:WBadgeAnimTypeNone];就可以调整位置

**Comment by weng1250** [comment]
@mg459046365 请问你用的是最新的1.2.2版本吗？无论使用showBadge的哪个接口都是可以调整位置的，showBadge接口仅仅是对其他更多参数接口的一层封装。我这边也试过了。请更新到最新版上再试试。欢迎追加issues
