### ISSUE TITLE
小红点clear后，再次show无效

### ISSUE THREAD

**Issue by GanWenPeng** [weng1250/WZLBadge#16]
亲，感谢你的WZLBadge，用着很爽，很佩服你。
今天在运行的时候发现，如果UIBarButtonItem clearBadge之后，如果再show，就怎么也show不出来，请问有办法解决吗？3Q

**Comment by weng1250** [comment]
谢谢你。针对你的问题，在clear之后如果想重新显示之前的badge有两种解决方法：方法1、重新走一遍showBadge的配置流程，也就是说将之前在showBadge的时候的属性设置代码重新调用一遍；方法2、使用1.2.3版本中新增的-resumeBdage接口恢复之前的badge。
