### ISSUE TITLE
badge位置问题

### ISSUE THREAD

**Issue by JohnLif** [weng1250/WZLBadge#20]
当我用UITabBarItem+WZLBadge.h这个类别的时候，修改了badgeContentOffset属性，使得badge的UILabel和UITabBarItem上的图片距离更近一些。这时如果这两个view有重叠时，重叠部分的badge会被tabbarItem的图片遮住，请问这个问题如何解决

**Comment by FishChong** [comment]
UITabBarItem+WZLBadge.h  Bade 的位置能不能默认就是跟系统的一样 而不用去设置它的偏移

**Comment by weng1250** [comment]
This bug was fixed in v1.2.5. Thanks your issue
