### ISSUE TITLE
Autolayout issue

### ISSUE THREAD

**Issue by fdddf** [weng1250/WZLBadge#21]
A customised button with text and imageView placed on the table view cell, and using Masonry for auto layout.
I want to show badge number upon the imageView. Call show badge function likes in the cellForRow atIndexPath.
cell.btn.iconImageView showBadgeWithStyle:WBadgeStyleNumber... 

Here the issue coming, the badge displays on the top left of the imageView. And I lookup the lib code, the badgeInit function try to get self.frame with zero. That's the bug I thoughts.
Am I clearly explained? Thx.

**Comment by wangchaodong** [comment]
i got the same problem , how did you fix it?
