### ISSUE TITLE
setBadgeFont invaild

### ISSUE THREAD

**Issue by new-soul** [weng1250/WZLBadge#22]
When I setBadgeFont for the badge,it always show me the default font.

**Comment by litt1e-p** [comment]
set the badgeFont after showBadge could work

**Comment by weng1250** [comment]
@litt1e-p  That`s right, because bage instance has not yet alloced before calling setBadgeFont:. This is a bug but it has will be fixed in version 1.2.6. Sorry to bother u.

**Comment by weng1250** [comment]
@new-soul

**Comment by litt1e-p** [comment]
glad to that🎉
