### ISSUE TITLE
badge不显示!!

### ISSUE THREAD

**Issue by fuchenxi** [weng1250/WZLBadge#28]
打印self.badge 为null, 其它属性也是null, 不知道是不是和什么冲突了, 前一个项目用就可以正常显示, 这个新项目就不行。查看视图层级, 没有badgeLabel这个控件, 什么情况会产生这种原因?

**Comment by weng1250** [comment]
是不是使用姿势不对，建议你断点一下- (void)badgeInit方法看有没有走到
