### ISSUE TITLE
位置调节无效，可以提供几种位置模式吗

### ISSUE THREAD

**Issue by iHTCboy** [weng1250/WZLBadge#3]
比如我是三个按钮并排，图片是在中间，但因为按钮宽度比较大，所以红点偏离图片很远了

**Comment by weng1250** [comment]
WZLBadge would consider pre-define several position modes, to make it easier to use. Welcome to provide more nice issue and advice. Thanks anagin.

**Comment by weng1250** [comment]
Bug is fixed in version 1.1 released.

**Comment by iHTCboy** [comment]
very good! thank you!

**Comment by weng1250** [comment]
You can make use of 'badgeCenterOffset' property to customize badge position as you want. Default origin position is right-top corner of your view.
