### ISSUE TITLE
红点的大小能支持定制吗？

### ISSUE THREAD

**Issue by LuYu001** [weng1250/WZLBadge#40]
显示数字的时候可以通过字体大小调整，但是一个红点的时候怎么设置半径？

**Comment by LuYu001** [comment]
好吧， 还是有办法的， 红点也使用number样式， 然后设置字体大小来控制大小， 字体颜色和背景颜色设置一样就行了

**Comment by weng1250** [comment]
你的方法也是可行的，不过太绕。目前已经支持，今天内会推新tag1.2.7支持原点半径大小调整
