### ISSUE TITLE
iOS 13适配问题

### ISSUE THREAD

**Issue by LitDragon** [weng1250/WZLBadge#69]
在iOS13，设置的badgeBgColor badgeTextColor badgeCenterOffset都失效，而且badge的位置还不对，超出了tabbar的位置，切换别的viewController后badge被切一半，选中的颜色和未选中的颜色也不一样
![image](https://user-images.githubusercontent.com/16676534/60697092-33975580-9f1b-11e9-8deb-b6da35ee335f.png)
![image](https://user-images.githubusercontent.com/16676534/60697100-3e51ea80-9f1b-11e9-816b-6abd9a9cd9c9.png)

**Comment by LitDragon** [comment]
本来是设置badge背景色是橙色的，现在没反应

**Comment by LixinQian** [comment]
遍历UITabBarButton的subViews发现只有在TabBar选中状态下才能取到UITabBarSwappableImageView，解决办法是修改为通过UITabBarButton的位置来设置红点的frame

**Comment by charlesYun** [comment]
> 遍历UITabBarButton的subViews发现只有在TabBar选中状态下才能取到UITabBarSwappableImageView，解决办法是修改为通过UITabBarButton的位置来设置红点的frame

我也遇到了这个问题，能说说具体怎么解决吗

**Comment by LitDragon** [comment]
不了了之
