### ISSUE TITLE
不能修改数值

### ISSUE THREAD

**Issue by JeansHuang** [weng1250/WZLBadge#9]
- (void)showNumberBadgeWithValue:(NSInteger)value{
    if (value < 0) {
        return;
    }
    [self badgeInit];
    if (self.badge.tag != WBadgeStyleNumber) {
        self.badge.tag = WBadgeStyleNumber;
        
        //maximun value allowed is 99. When the value is greater than 99, "99+" will be shown.
        if (value >=100) {
            self.badge.text = @"99+";
        } else {
            self.badge.text = [NSString stringWithFormat:@"%@", @(value)];
        }
        [self adjustLabelWidth:self.badge];
        self.badge.width = self.badge.width - 4;
        self.badge.height = 12;
        if (self.badge.width < self.badge.height) {
            self.badge.width = self.badge.height;
        }
        
        self.badge.center = CGPointMake(self.width + 2 + self.badgeCenterOffset.x, self.badgeCenterOffset.y);
        self.badge.font = [UIFont boldSystemFontOfSize:9];
        self.badge.layer.cornerRadius = self.badge.height / 2;
    }
    self.badge.hidden = NO;
    if (value == 0) {
        self.badge.hidden = YES;
    }
}
    

问题应该在于这里。可以看出，再次调用，value不会重新赋值。因此造成数字有更新，但是调用无反应。

**Comment by weng1250** [comment]
fixed
